### ISSUE TITLE
Add wait_until_weaviate_is_ready function

### ISSUE THREAD

**Issue by dirkkul** [weaviate/weaviate-go-client#112]
When starting it can take a few seconds until it is ready and the client can "use" it. Currently it's in the responsibility of the user to wait until the weavaite is ready. 

To improve the UX, we should let the client wait (with a timeout) until weaviate is ready and "v1/.well-known/ready" returns 404

Note: There is something comparable in the tests in `v4/weaviate/testenv/environment.go`, here is a PR for the python client that [implements something comparable](https://github.com/weaviate/weaviate-python-client/pull/217)

**Comment by Sasmuin** [comment]
I will try this.
