### ISSUE TITLE
Missing BM25 and Hybrid argument builders in GraphQL API

### ISSUE THREAD

**Issue by antas-marcin** [weaviate/weaviate-go-client#113]

**Comment by shreyanshshah27** [comment]
@antas-marcin @dirkkul Can you please add more description? I'm not able to reproduce this issue with weaviate `1.17.2` or `preview-replace-shardingconfig-replicas-with-replication-factor-29e987d` though I can see the same issue in weaviate `1.14.0`. Not sure the reason, probably in weaviate `1.14.0` BM25 and Hybrid search weren't present. 

I believe you might have more insights on this, please share your suggestions.

**Comment by dirkkul** [comment]
@etiennedi That bug report came from you, could you add an example of what doesn't work?

**Comment by etiennedi** [comment]
![image](https://user-images.githubusercontent.com/8974479/215586803-78cd5c59-65b2-486c-81e5-e85537657f2e.png)

![image](https://user-images.githubusercontent.com/8974479/215586843-507fb906-a506-4527-850c-7798b2a2142e.png)

![image](https://user-images.githubusercontent.com/8974479/215586866-fe1d9077-a0b1-472b-969e-d3f414096f81.png)

**Comment by shreyanshshah27** [comment]
Thanks for describing the issue, should be an easy fix. Will add these query builders.

**Comment by dirkkul** [comment]
closes https://github.com/weaviate/weaviate-go-client/pull/116
