### ISSUE TITLE
Add builder for generative openai module

### ISSUE THREAD

**Issue by dirkkul** [weaviate/weaviate-go-client#120]
Using the generative module is currently possible, but has a bad UX (see examples below). Its usage could be improved by adding a builder for this kind of query.

Note:

- You need at least this weaviate version: `semitechnologies/weaviate:preview-new-module-generative-openai-c9bcad8`
- The module `generative-openai` needs to be enabled using `ENABLE_MODULES=generative-openai`
- You need an openai API key:`OPENAI_APIKEY=some_key`

Example:
```
singleResult := []graphql.Field{
	{
		Name: "_additional",
		Fields: []graphql.Field{
			{
				Name: "generate(singleResult:{ prompt: \"based on {review} when is this wine ready to drink?\" })",
				Fields: []graphql.Field{
					{Name: "singleResult"},
				},
			},
		},
	},
}
groupedResult := []graphql.Field{
	{
		Name: "_additional",
		Fields: []graphql.Field{
		{
			Name: "generate(groupedResult:{ task: \"desribe the difference between young and old koehler wine\" })",
			Fields: []graphql.Field{
				{Name: "groupedResult"},
			},
			},
		},
	},
}
```

**Comment by antas-marcin** [comment]
When implementing this builder for `generative-openai` additional argument I would think about a generic approach (common approach) on introducing this kind of builders

**Comment by shreyanshshah27** [comment]
Hey @dirkkul, this looks interesting, but couldn't quite understand what all needs to be done. Is there support for same builder has been added in any other client library?

**Comment by dirkkul** [comment]
Hi @shreyanshshah27 

is the issue unclear?
I can also come up with an example API, but I'm somewhat busy at the moment so it would take a bit.

**Comment by shreyanshshah27** [comment]
Hey @dirkkul

Thanks for the follow up. Honestly I got super busy with some other work and this totally slipped my mind xD. Over the weekend I'll have a look on the references you've shared for this and I'll definitely get back to you with some ideas/query before Monday.

**Comment by dirkkul** [comment]
Hi @shreyanshshah27 

alright, absolutely no pressure. Just wanted to check-in :)

**Comment by shreyanshshah27** [comment]
Hey @dirkkul 

I was playing around with this new module to learn and understand it better and this module is working seamlessly and I thing this is gonna be a game changer.

I've some ideas on the builder implementation, I'll try to summarize them and I'll share those with you ASAP.

I also found a very minor bug in this module's curl example in both single result and grouped result. This PR should fix that : https://github.com/weaviate/weaviate-io/pull/459. It would be great if you can review that.

**Comment by dirkkul** [comment]
https://github.com/weaviate/weaviate-go-client/pull/124
