### ISSUE TITLE
[Refactor] Build URL query params in a more idiomatic way

### ISSUE THREAD

**Issue by etiennedi** [weaviate/weaviate-go-client#127]
URLs are currently built by concatenating strings, e.g: 
![image](https://user-images.githubusercontent.com/8974479/221626404-10a23a68-0881-49e9-9329-47a329b56ee8.png)

This could use `url.URL` and similar types from the stdlib. This would:
* make it easier to read
* be more idiomatic go
* handle encoding edge cases better

**Comment by Sasmuin** [comment]
I will try this.
