### ISSUE TITLE
Support offset parameter in Object List to support pagination

### ISSUE THREAD

**Issue by jlewi** [weaviate/weaviate-go-client#129]
The list method uses the offset query parameter to do pagination
https://weaviate.io/developers/weaviate/api/rest/objects#list-all-data-objects

It looks like the code is missing a method e.g. `WithOffset` to actually set the offset. buildPathParams looks like it is missing code to set the offset as well.
https://github.com/weaviate/weaviate-go-client/blob/9dc91c57f9b1963cbdcfda1cf2e129fe55deb9b7/weaviate/data/objectsGetter.go#L128

It doesn't look like WithAdditionalParameters is the right way to do this; it looks like that method is setting the value of the `include` argument. 

Related to #127

**Comment by Sasmuin** [comment]
I will try this.
