### ISSUE TITLE
Fix TestAuthBearerToken and TestAuth_UserPW tests

### ISSUE THREAD

**Issue by antas-marcin** [weaviate/weaviate-go-client#163]
Both `TestAuthBearerToken` and `TestAuth_UserPW` tests are hanging forever. For now those tests are skipped.

**Comment by antas-marcin** [comment]
We should revisit this [PR](https://github.com/weaviate/weaviate-go-client/pull/154/files) implementation in this issue

**Comment by dirkkul** [comment]
closed by https://github.com/weaviate/weaviate-go-client/pull/170
