### ISSUE TITLE
WARNING: Usage of objects paths with class query parameter is not supported in Weaviate 1.18.2.

### ISSUE THREAD

**Issue by twang2218** [weaviate/weaviate-go-client#169]
I believe the `class` query parameter IS supported in Weaviate 1.18.2, however, my following code still trigger this warning message.

```go
	resp, err := w.client.Data().ObjectsGetter().
		WithClassName(w.IndexName).
		WithAdditional("vector").
		WithLimit(10000).
		Do(ctx)
```

The error messages are:

```js
WARNING: Usage of objects paths with class query parameter is not supported in Weaviate 1.18.2. class query parameter is ignored
```

After I checked the related code:

https://github.com/weaviate/weaviate-go-client/blob/46038a0dbbc46a4e2478e609b012cea3b2ddd79e/weaviate/data/objectsGetter.go#L162-L169

I think it might be wrong, the code should be:

```go
	if len(getter.id) == 0 && len(getter.className) > 0 {
		if getter.dbVersionSupport.SupportsClassNameNamespacedEndpoints() {
			pathParams.Set("class", getter.className)
		} else {
			getter.dbVersionSupport.WarnNotSupportedClassParameterInEndpointsForObjects()
		}
	}
```

Is there anything I'm missing?

**Comment by dirkkul** [comment]
should be fixed with 4.9.0 :)
