### ISSUE TITLE
Support Embedded Weaviate deployment model

### ISSUE THREAD

**Issue by xiaonerner0821** [weaviate/weaviate-go-client#229]
Do you have any plans to support Embedded Weaviate deployment model？I'm looking forward to use it in my desktop application.

**Comment by dirkkul** [comment]
> Do you have any plans to support Embedded Weaviate deployment model

No, no plans and I don't think we will have the resources to do this. Embedded is mainly designed to be used in notebook environments and AFAIK there are none for go
