### ISSUE TITLE
Support querying with multiple classes at once

### ISSUE THREAD

**Issue by parkerduckworth** [weaviate/weaviate-go-client#49]
Currently querying with only one class is supported. Queries like this are not currently possible:

```
{
  Get {
    ClassOne {
      field
    }
    ClassTwo {
      field
    }
  }
}
```

---

The change should be relatively simple.

The `GetBuilder` type can only support one class by design:

```
type GetBuilder struct {
	connection rest
	className  string
	withFields string

	includesFilterClause bool // true if brackets behind class is needed
	withWhereFilter      string
	includesLimit        bool
	limit                int
	includesOffset       bool
	offset               int
	withNearTextFilter   *NearTextArgumentBuilder
	withNearVectorFilter string
	withNearObjectFilter *NearObjectArgumentBuilder
	withGroupFilter      string
	withAskFilter        *AskArgumentBuilder
	withNearImageFilter  *NearImageArgumentBuilder
}
```

So each time you call `WithClassName`, (or any other query modifier), it’s just resetting the `GetBuilder.className` field. What needs to change is that the GetBuilder can look something like this:

```
type GetBuilder struct {
	ClassBuilders []*ClassBuilder
}

type ClassBuilder struct {
	connection rest
	className  string
	withFields string

	includesFilterClause bool // true if brackets behind class is needed
	withWhereFilter      string
	includesLimit        bool
	limit                int
	includesOffset       bool
	offset               int
	withNearTextFilter   *NearTextArgumentBuilder
	withNearVectorFilter string
	withNearObjectFilter *NearObjectArgumentBuilder
	withGroupFilter      string
	withAskFilter        *AskArgumentBuilder
	withNearImageFilter  *NearImageArgumentBuilder
}
```

**Comment by shreyanshshah27** [comment]
Hey @parkerduckworth, I'm new to this repo/project and wanted to get idea about this code-base and eventually start contributing. This seems like a good entry point for me. So I just wanted to confirm whether this issue is still open or this has been already resolved.

**Comment by parkerduckworth** [comment]
Hey @shreyanshshah27 this issue is still open and available 🙂

**Comment by shreyanshshah27** [comment]
Thanks for your quick response @parkerduckworth. I've tried to add this feature but instead of using `[]*ClassBuilder` as suggested by you, I am using `map[string]*ClassBuilder`, and in the long run I believe this will be a better solution. Requesting you and all other contributors to review this PR and provide their comments and inputs.

**Comment by dirkkul** [comment]
https://github.com/weaviate/weaviate-go-client/pull/106
